=begin
#Commerce Platform API

#RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments. 

The version of the OpenAPI document: 1.8.0

Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'date'
require 'time'

module PCPServerSDK
  class UnscheduledCardOnFileRequestor
    MERCHANT_INITIATED = "merchantInitiated".freeze
    CARDHOLDER_INITIATED = "cardholderInitiated".freeze

    def self.all_vars
      @all_vars ||= [MERCHANT_INITIATED, CARDHOLDER_INITIATED].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if UnscheduledCardOnFileRequestor.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #UnscheduledCardOnFileRequestor"
    end
  end
end
