module PCPServerSDK
  module Models
    class StatusValue < PCPServerSDK::ApiEnum
      CREATED = "CREATED".freeze
      CANCELLED = "CANCELLED".freeze
      REJECTED = "REJECTED".freeze
      REJECTED_CAPTURE = "REJECTED_CAPTURE".freeze
      REDIRECTED = "REDIRECTED".freeze
      PENDING_PAYMENT = "PENDING_PAYMENT".freeze
      PENDING_COMPLETION = "PENDING_COMPLETION".freeze
      PENDING_CAPTURE = "PENDING_CAPTURE".freeze
      AUTHORIZATION_REQUESTED = "AUTHORIZATION_REQUESTED".freeze
      CAPTURE_REQUESTED = "CAPTURE_REQUESTED".freeze
      CAPTURED = "CAPTURED".freeze
      REVERSED = "REVERSED".freeze
      REFUND_REQUESTED = "REFUND_REQUESTED".freeze
      REFUNDED = "REFUNDED".freeze
      REJECTED_REFUND = "REJECTED_REFUND".freeze
      CANCELLATION_REQUESTED = "CANCELLATION_REQUESTED".freeze
      PAUSED = "PAUSED".freeze
      CHARGEBACKED = "CHARGEBACKED".freeze
      CHARGEBACK_REVERSED = "CHARGEBACK_REVERSED".freeze
      ACCOUNT_CREDITED = "ACCOUNT_CREDITED".freeze
      ACCOUNT_DEBITED = "ACCOUNT_DEBITED".freeze
      PAYOUT_REQUESTED = "PAYOUT_REQUESTED".freeze
      REJECTED_CREDIT = "REJECTED_CREDIT".freeze
    end
  end
end
