=begin
#Commerce Platform API

#RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments. 

The version of the OpenAPI document: 1.8.0

Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

# Common files
require 'PCP-server-Ruby-SDK/api_client'
require 'PCP-server-Ruby-SDK/api_error'
require 'PCP-server-Ruby-SDK/version'
require 'PCP-server-Ruby-SDK/configuration'

# Models
require 'PCP-server-Ruby-SDK/models/api_error'
require 'PCP-server-Ruby-SDK/models/address'
require 'PCP-server-Ruby-SDK/models/address_personal'
require 'PCP-server-Ruby-SDK/models/allowed_payment_actions'
require 'PCP-server-Ruby-SDK/models/amount_of_money'
require 'PCP-server-Ruby-SDK/models/apple_payment_data_token_header_information'
require 'PCP-server-Ruby-SDK/models/apple_payment_data_token_information'
require 'PCP-server-Ruby-SDK/models/authorization_mode'
require 'PCP-server-Ruby-SDK/models/bank_account_information'
require 'PCP-server-Ruby-SDK/models/cancel_item'
require 'PCP-server-Ruby-SDK/models/cancel_payment_request'
require 'PCP-server-Ruby-SDK/models/cancel_payment_response'
require 'PCP-server-Ruby-SDK/models/cancel_request'
require 'PCP-server-Ruby-SDK/models/cancel_response'
require 'PCP-server-Ruby-SDK/models/cancel_type'
require 'PCP-server-Ruby-SDK/models/cancellation_reason'
require 'PCP-server-Ruby-SDK/models/capture_output'
require 'PCP-server-Ruby-SDK/models/capture_payment_request'
require 'PCP-server-Ruby-SDK/models/capture_payment_response'
require 'PCP-server-Ruby-SDK/models/card_fraud_results'
require 'PCP-server-Ruby-SDK/models/card_info'
require 'PCP-server-Ruby-SDK/models/card_payment_details'
require 'PCP-server-Ruby-SDK/models/card_payment_method_specific_input'
require 'PCP-server-Ruby-SDK/models/card_payment_method_specific_output'
require 'PCP-server-Ruby-SDK/models/card_recurrence_details'
require 'PCP-server-Ruby-SDK/models/cart_item_input'
require 'PCP-server-Ruby-SDK/models/cart_item_invoice_data'
require 'PCP-server-Ruby-SDK/models/cart_item_order_status'
require 'PCP-server-Ruby-SDK/models/cart_item_patch'
require 'PCP-server-Ruby-SDK/models/cart_item_result'
require 'PCP-server-Ruby-SDK/models/cart_item_status'
require 'PCP-server-Ruby-SDK/models/checkout_references'
require 'PCP-server-Ruby-SDK/models/checkout_response'
require 'PCP-server-Ruby-SDK/models/checkouts_response'
require 'PCP-server-Ruby-SDK/models/commerce_case_response'
require 'PCP-server-Ruby-SDK/models/company_information'
require 'PCP-server-Ruby-SDK/models/complete_financing_payment_method_specific_input'
require 'PCP-server-Ruby-SDK/models/complete_payment_method_specific_input'
require 'PCP-server-Ruby-SDK/models/complete_payment_request'
require 'PCP-server-Ruby-SDK/models/complete_payment_response'
require 'PCP-server-Ruby-SDK/models/contact_details'
require 'PCP-server-Ruby-SDK/models/create_checkout_request'
require 'PCP-server-Ruby-SDK/models/create_checkout_response'
require 'PCP-server-Ruby-SDK/models/create_commerce_case_request'
require 'PCP-server-Ruby-SDK/models/create_commerce_case_response'
require 'PCP-server-Ruby-SDK/models/create_payment_response'
require 'PCP-server-Ruby-SDK/models/customer'
require 'PCP-server-Ruby-SDK/models/customer_device'
require 'PCP-server-Ruby-SDK/models/deliver_item'
require 'PCP-server-Ruby-SDK/models/deliver_request'
require 'PCP-server-Ruby-SDK/models/deliver_response'
require 'PCP-server-Ruby-SDK/models/deliver_type'
require 'PCP-server-Ruby-SDK/models/delivery_information'
require 'PCP-server-Ruby-SDK/models/error_response'
require 'PCP-server-Ruby-SDK/models/extended_checkout_status'
require 'PCP-server-Ruby-SDK/models/financing_payment_method_specific_input'
require 'PCP-server-Ruby-SDK/models/financing_payment_method_specific_output'
require 'PCP-server-Ruby-SDK/models/installment_option'
require 'PCP-server-Ruby-SDK/models/link_information'
require 'PCP-server-Ruby-SDK/models/mandate_recurrence_type'
require 'PCP-server-Ruby-SDK/models/merchant_action'
require 'PCP-server-Ruby-SDK/models/mobile_payment_method_specific_input'
require 'PCP-server-Ruby-SDK/models/mobile_payment_method_specific_output'
require 'PCP-server-Ruby-SDK/models/order'
require 'PCP-server-Ruby-SDK/models/order_item'
require 'PCP-server-Ruby-SDK/models/order_line_details_input'
require 'PCP-server-Ruby-SDK/models/order_line_details_patch'
require 'PCP-server-Ruby-SDK/models/order_line_details_result'
require 'PCP-server-Ruby-SDK/models/order_request'
require 'PCP-server-Ruby-SDK/models/order_response'
require 'PCP-server-Ruby-SDK/models/order_type'
require 'PCP-server-Ruby-SDK/models/patch_checkout_request'
require 'PCP-server-Ruby-SDK/models/patch_commerce_case_request'
require 'PCP-server-Ruby-SDK/models/payment_channel'
require 'PCP-server-Ruby-SDK/models/payment_creation_output'
require 'PCP-server-Ruby-SDK/models/payment_event'
require 'PCP-server-Ruby-SDK/models/payment_execution'
require 'PCP-server-Ruby-SDK/models/payment_execution_request'
require 'PCP-server-Ruby-SDK/models/payment_execution_specific_input'
require 'PCP-server-Ruby-SDK/models/payment_information_request'
require 'PCP-server-Ruby-SDK/models/payment_information_response'
require 'PCP-server-Ruby-SDK/models/payment_method_specific_input'
require 'PCP-server-Ruby-SDK/models/payment_output'
require 'PCP-server-Ruby-SDK/models/payment_product320_specific_input'
require 'PCP-server-Ruby-SDK/models/payment_product3391_specific_input'
require 'PCP-server-Ruby-SDK/models/payment_product3391_specific_output'
require 'PCP-server-Ruby-SDK/models/payment_product3392_specific_input'
require 'PCP-server-Ruby-SDK/models/payment_product771_specific_output'
require 'PCP-server-Ruby-SDK/models/payment_product840_customer_account'
require 'PCP-server-Ruby-SDK/models/payment_product840_specific_output'
require 'PCP-server-Ruby-SDK/models/payment_references'
require 'PCP-server-Ruby-SDK/models/payment_response'
require 'PCP-server-Ruby-SDK/models/payment_status_output'
require 'PCP-server-Ruby-SDK/models/payment_type'
require 'PCP-server-Ruby-SDK/models/payout_output'
require 'PCP-server-Ruby-SDK/models/payout_response'
require 'PCP-server-Ruby-SDK/models/personal_information'
require 'PCP-server-Ruby-SDK/models/personal_name'
require 'PCP-server-Ruby-SDK/models/positive_amount_of_money'
require 'PCP-server-Ruby-SDK/models/processing_mandate_information'
require 'PCP-server-Ruby-SDK/models/product_type'
require 'PCP-server-Ruby-SDK/models/redirect_data'
require 'PCP-server-Ruby-SDK/models/redirect_payment_method_specific_input'
require 'PCP-server-Ruby-SDK/models/redirect_payment_method_specific_output'
require 'PCP-server-Ruby-SDK/models/redirect_payment_product840_specific_input'
require 'PCP-server-Ruby-SDK/models/redirection_data'
require 'PCP-server-Ruby-SDK/models/references'
require 'PCP-server-Ruby-SDK/models/refund_error_response'
require 'PCP-server-Ruby-SDK/models/refund_output'
require 'PCP-server-Ruby-SDK/models/refund_payment_response'
require 'PCP-server-Ruby-SDK/models/refund_request'
require 'PCP-server-Ruby-SDK/models/return_information'
require 'PCP-server-Ruby-SDK/models/return_item'
require 'PCP-server-Ruby-SDK/models/return_request'
require 'PCP-server-Ruby-SDK/models/return_response'
require 'PCP-server-Ruby-SDK/models/return_type'
require 'PCP-server-Ruby-SDK/models/sepa_direct_debit_payment_method_specific_input'
require 'PCP-server-Ruby-SDK/models/sepa_direct_debit_payment_method_specific_output'
require 'PCP-server-Ruby-SDK/models/sepa_direct_debit_payment_product771_specific_input'
require 'PCP-server-Ruby-SDK/models/shipping'
require 'PCP-server-Ruby-SDK/models/shopping_cart_input'
require 'PCP-server-Ruby-SDK/models/shopping_cart_patch'
require 'PCP-server-Ruby-SDK/models/shopping_cart_result'
require 'PCP-server-Ruby-SDK/models/status_category_value'
require 'PCP-server-Ruby-SDK/models/status_checkout'
require 'PCP-server-Ruby-SDK/models/status_output'
require 'PCP-server-Ruby-SDK/models/status_value'
require 'PCP-server-Ruby-SDK/models/three_d_secure_results'
require 'PCP-server-Ruby-SDK/models/transaction_channel'
require 'PCP-server-Ruby-SDK/models/unscheduled_card_on_file_requestor'
require 'PCP-server-Ruby-SDK/models/unscheduled_card_on_file_sequence_indicator'

# APIs
require 'PCP-server-Ruby-SDK/api/checkout_api'
require 'PCP-server-Ruby-SDK/api/commerce_case_api'
require 'PCP-server-Ruby-SDK/api/order_management_checkout_actions_api'
require 'PCP-server-Ruby-SDK/api/payment_execution_api'
require 'PCP-server-Ruby-SDK/api/payment_information_api'

module PCPServerSDK
  class << self
    # Customize default settings for the SDK using block.
    #   PCPServerSDK.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
