require 'PCP-ServerSDK-ruby/api_client'
require 'PCP-ServerSDK-ruby/api_error'
require 'PCP-ServerSDK-ruby/api_model'
require 'PCP-ServerSDK-ruby/api_enum'
require 'PCP-ServerSDK-ruby/version'
require 'PCP-ServerSDK-ruby/configuration'

# Models
require 'PCP-ServerSDK-ruby/models/api_error'
require 'PCP-ServerSDK-ruby/models/address'
require 'PCP-ServerSDK-ruby/models/address_personal'
require 'PCP-ServerSDK-ruby/models/allowed_payment_actions'
require 'PCP-ServerSDK-ruby/models/amount_of_money'
require 'PCP-ServerSDK-ruby/models/apple_payment_data_token_header_information'
require 'PCP-ServerSDK-ruby/models/apple_payment_data_token_information'
require 'PCP-ServerSDK-ruby/models/authorization_mode'
require 'PCP-ServerSDK-ruby/models/bank_account_information'
require 'PCP-ServerSDK-ruby/models/cancel_item'
require 'PCP-ServerSDK-ruby/models/cancel_payment_request'
require 'PCP-ServerSDK-ruby/models/cancel_payment_response'
require 'PCP-ServerSDK-ruby/models/cancel_request'
require 'PCP-ServerSDK-ruby/models/cancel_response'
require 'PCP-ServerSDK-ruby/models/cancel_type'
require 'PCP-ServerSDK-ruby/models/cancellation_reason'
require 'PCP-ServerSDK-ruby/models/capture_output'
require 'PCP-ServerSDK-ruby/models/capture_payment_request'
require 'PCP-ServerSDK-ruby/models/capture_payment_response'
require 'PCP-ServerSDK-ruby/models/card_fraud_results'
require 'PCP-ServerSDK-ruby/models/card_info'
require 'PCP-ServerSDK-ruby/models/card_payment_details'
require 'PCP-ServerSDK-ruby/models/card_payment_method_specific_input'
require 'PCP-ServerSDK-ruby/models/card_payment_method_specific_output'
require 'PCP-ServerSDK-ruby/models/card_recurrence_details'
require 'PCP-ServerSDK-ruby/models/cart_item_input'
require 'PCP-ServerSDK-ruby/models/cart_item_invoice_data'
require 'PCP-ServerSDK-ruby/models/cart_item_order_status'
require 'PCP-ServerSDK-ruby/models/cart_item_patch'
require 'PCP-ServerSDK-ruby/models/cart_item_result'
require 'PCP-ServerSDK-ruby/models/cart_item_status'
require 'PCP-ServerSDK-ruby/models/checkout_references'
require 'PCP-ServerSDK-ruby/models/checkout_response'
require 'PCP-ServerSDK-ruby/models/checkouts_response'
require 'PCP-ServerSDK-ruby/models/commerce_case_response'
require 'PCP-ServerSDK-ruby/models/company_information'
require 'PCP-ServerSDK-ruby/models/complete_financing_payment_method_specific_input'
require 'PCP-ServerSDK-ruby/models/complete_payment_method_specific_input'
require 'PCP-ServerSDK-ruby/models/complete_payment_request'
require 'PCP-ServerSDK-ruby/models/complete_payment_response'
require 'PCP-ServerSDK-ruby/models/contact_details'
require 'PCP-ServerSDK-ruby/models/create_checkout_request'
require 'PCP-ServerSDK-ruby/models/create_checkout_response'
require 'PCP-ServerSDK-ruby/models/create_commerce_case_request'
require 'PCP-ServerSDK-ruby/models/create_commerce_case_response'
require 'PCP-ServerSDK-ruby/models/create_payment_response'
require 'PCP-ServerSDK-ruby/models/customer'
require 'PCP-ServerSDK-ruby/models/customer_device'
require 'PCP-ServerSDK-ruby/models/deliver_item'
require 'PCP-ServerSDK-ruby/models/deliver_request'
require 'PCP-ServerSDK-ruby/models/deliver_response'
require 'PCP-ServerSDK-ruby/models/deliver_type'
require 'PCP-ServerSDK-ruby/models/delivery_information'
require 'PCP-ServerSDK-ruby/models/error_response'
require 'PCP-ServerSDK-ruby/models/extended_checkout_status'
require 'PCP-ServerSDK-ruby/models/financing_payment_method_specific_input'
require 'PCP-ServerSDK-ruby/models/financing_payment_method_specific_output'
require 'PCP-ServerSDK-ruby/models/installment_option'
require 'PCP-ServerSDK-ruby/models/link_information'
require 'PCP-ServerSDK-ruby/models/mandate_recurrence_type'
require 'PCP-ServerSDK-ruby/models/merchant_action'
require 'PCP-ServerSDK-ruby/models/mobile_payment_method_specific_input'
require 'PCP-ServerSDK-ruby/models/mobile_payment_method_specific_output'
require 'PCP-ServerSDK-ruby/models/order'
require 'PCP-ServerSDK-ruby/models/order_item'
require 'PCP-ServerSDK-ruby/models/order_line_details_input'
require 'PCP-ServerSDK-ruby/models/order_line_details_patch'
require 'PCP-ServerSDK-ruby/models/order_line_details_result'
require 'PCP-ServerSDK-ruby/models/order_request'
require 'PCP-ServerSDK-ruby/models/order_response'
require 'PCP-ServerSDK-ruby/models/order_type'
require 'PCP-ServerSDK-ruby/models/patch_checkout_request'
require 'PCP-ServerSDK-ruby/models/patch_commerce_case_request'
require 'PCP-ServerSDK-ruby/models/payment_channel'
require 'PCP-ServerSDK-ruby/models/payment_creation_output'
require 'PCP-ServerSDK-ruby/models/payment_event'
require 'PCP-ServerSDK-ruby/models/payment_execution'
require 'PCP-ServerSDK-ruby/models/payment_execution_request'
require 'PCP-ServerSDK-ruby/models/payment_execution_specific_input'
require 'PCP-ServerSDK-ruby/models/payment_information_request'
require 'PCP-ServerSDK-ruby/models/payment_information_response'
require 'PCP-ServerSDK-ruby/models/payment_method_specific_input'
require 'PCP-ServerSDK-ruby/models/payment_output'
require 'PCP-ServerSDK-ruby/models/payment_product320_specific_input'
require 'PCP-ServerSDK-ruby/models/payment_product3391_specific_input'
require 'PCP-ServerSDK-ruby/models/payment_product3391_specific_output'
require 'PCP-ServerSDK-ruby/models/payment_product3392_specific_input'
require 'PCP-ServerSDK-ruby/models/payment_product771_specific_output'
require 'PCP-ServerSDK-ruby/models/payment_product840_customer_account'
require 'PCP-ServerSDK-ruby/models/payment_product840_specific_output'
require 'PCP-ServerSDK-ruby/models/payment_references'
require 'PCP-ServerSDK-ruby/models/payment_response'
require 'PCP-ServerSDK-ruby/models/payment_status_output'
require 'PCP-ServerSDK-ruby/models/payment_type'
require 'PCP-ServerSDK-ruby/models/payout_output'
require 'PCP-ServerSDK-ruby/models/payout_response'
require 'PCP-ServerSDK-ruby/models/personal_information'
require 'PCP-ServerSDK-ruby/models/personal_name'
require 'PCP-ServerSDK-ruby/models/positive_amount_of_money'
require 'PCP-ServerSDK-ruby/models/processing_mandate_information'
require 'PCP-ServerSDK-ruby/models/product_type'
require 'PCP-ServerSDK-ruby/models/redirect_data'
require 'PCP-ServerSDK-ruby/models/redirect_payment_method_specific_input'
require 'PCP-ServerSDK-ruby/models/redirect_payment_method_specific_output'
require 'PCP-ServerSDK-ruby/models/redirect_payment_product840_specific_input'
require 'PCP-ServerSDK-ruby/models/redirection_data'
require 'PCP-ServerSDK-ruby/models/references'
require 'PCP-ServerSDK-ruby/models/refund_error_response'
require 'PCP-ServerSDK-ruby/models/refund_output'
require 'PCP-ServerSDK-ruby/models/refund_payment_response'
require 'PCP-ServerSDK-ruby/models/refund_request'
require 'PCP-ServerSDK-ruby/models/return_information'
require 'PCP-ServerSDK-ruby/models/return_item'
require 'PCP-ServerSDK-ruby/models/return_request'
require 'PCP-ServerSDK-ruby/models/return_response'
require 'PCP-ServerSDK-ruby/models/return_type'
require 'PCP-ServerSDK-ruby/models/sepa_direct_debit_payment_method_specific_input'
require 'PCP-ServerSDK-ruby/models/sepa_direct_debit_payment_method_specific_output'
require 'PCP-ServerSDK-ruby/models/sepa_direct_debit_payment_product771_specific_input'
require 'PCP-ServerSDK-ruby/models/shipping'
require 'PCP-ServerSDK-ruby/models/shopping_cart_input'
require 'PCP-ServerSDK-ruby/models/shopping_cart_patch'
require 'PCP-ServerSDK-ruby/models/shopping_cart_result'
require 'PCP-ServerSDK-ruby/models/status_category_value'
require 'PCP-ServerSDK-ruby/models/status_checkout'
require 'PCP-ServerSDK-ruby/models/status_output'
require 'PCP-ServerSDK-ruby/models/status_value'
require 'PCP-ServerSDK-ruby/models/three_d_secure_results'
require 'PCP-ServerSDK-ruby/models/transaction_channel'
require 'PCP-ServerSDK-ruby/models/unscheduled_card_on_file_requestor'
require 'PCP-ServerSDK-ruby/models/unscheduled_card_on_file_sequence_indicator'

# APIs
require 'PCP-ServerSDK-ruby/api/checkout_api'
require 'PCP-ServerSDK-ruby/api/commerce_case_api'
require 'PCP-ServerSDK-ruby/api/order_management_checkout_actions_api'
require 'PCP-ServerSDK-ruby/api/payment_execution_api'
require 'PCP-ServerSDK-ruby/api/payment_information_api'

module PCPServerSDK
  class << self
    # Customize default settings for the SDK using block.
    #   PCPServerSDK.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
