# .github/workflows/ruby.yml

name: Publish to Rubygems

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4   
        with:
          fetch-depth: 0   
      - name: Build Gem
        run: ./scripts.sh build
      - name: Publish Gem
        run: ./scripts.sh publish ${{ secrets.RUBYGEMS_API_KEY }}