# .github/workflows/ruby.yml

name: Ruby Test and SonarCloud

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0"
          bundler-cache: true

      - name: Lint via rubocop
        run: ./scripts.sh lint          

  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        ruby-version: ["3.0", "3.1", "3.2", "3.4"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Test
        run: ./scripts.sh test  

  sonar:
    runs-on: ubuntu-20.04
    needs: test   
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.0" 
        bundler-cache: true 

    - name: Test
      run: ./scripts.sh test  

    - name: fix code coverage paths
      working-directory: ./coverage
      run: |
          sed -i 's@'$GITHUB_WORKSPACE'@/github/workspace@g' coverage.json

    - name: Run SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@v3.0.0
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}