# .github/workflows/ruby.yml

name: Ruby Test and SonarCloud

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0.0' # Specify the Ruby version you are using
        bundler-cache: true  # Caches 'bundle install' automatically

    - name: Install dependencies
      run: bundle install

    - name: Run RuboCop
      run: bundle exec rubocop

    - name: Run tests
      run: bundle exec rake test

    - name: Run SonarCloud Scan
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Reference the SONAR_TOKEN secret
      run: |
        sonar-scanner -Dsonar.login=${{ secrets.SONAR_TOKEN }} 
